---

baseurl: "/"
languageCode: "fr-fr"
title: "Cloud Foundry, du sol au plafond !"
theme: "hugo-theme-pivotal-revealjs"

params:

  logo: img/cf.png

  titleSlide:
    subtitle: "La fondamentaux de Cloud Foundry"
    notes: |

      Une formation pour débuter sur Cloud Foundry.
