baseurl = "/"
languageCode = "fr-fr"
title = "Cloud Native et Microservices"
theme = "hugo-material-docs"
metadataformat = "yaml"
# canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-67001027-2"

[params]
	# General information
	description = "Formation Cloud Foundry - Cloud Native et Microservices"
	copyright = "Fondation CF et Gstack.io, Tous droits réservés."

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/gstackio/formations-cf"

	version = "1.0.1"
  headerLogo = "/img/cf-white.png"
  logo = "img/cf-rabbit.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "blue-grey"
    	accent  = "blue"

    [params.font]
    	text = "Roboto"
    	code = "Roboto Mono"


[social]
	github  = "gstackio/formations-cf"

[[menu.main]]
	name   = "Bienvenue"
	url    = ""
	weight = 1

[[menu.main]]
	name   = "Pré-requis"
	url    = "prereqs/"
	weight = 10

[[menu.main]]
	name   = "Sommaire"
	url    = "agenda/"
	weight = 20

[[menu.main]]
	name   = "Compléments"
	url    = "resources/"
	weight = 30

[[menu.main]]
	name   = "Notes"
	url    = "notes/"
	weight = 35

[[menu.main]]
	name   = "License"
	url    = "http://www.apache.org/licenses/LICENSE-2.0"
	weight = 40


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
