---

baseurl: "/slides"
languageCode: "fr-fr"
title: "Evoluer vers le 'Cloud Native'"
theme: "hugo-theme-pivotal-revealjs"

params:

  logo: img/cf.png

  titleSlide:
    subtitle: "Adopter le 'Cloud Native'"
    notes: |

      Dans cette section, nous allons découvrir comment évoluer vers la mouvance 'Cloud Native'.
